#! /bin/sh


"$HOME"/.config/bspwm/autostart.sh &

#cbatticon -u 10 -x "notify-send $(cat /sys/class/power_supply/BAT1/capacity)" &
# Scratch term
#st -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating
#bspc rule -a scratchterm sticky=on state=floating hidden=on

#### WORKSPACES AND BORDERS ####
 
#Monitor allocation and their workspaces
[ $(xrandr -q | grep ' connected ' | awk '{print $1}' | wc -l) -eq 2 ] && (bspc monitor eDP -d 1 2 3 4 5; bspc monitor HDMI-A-0 -d 6 7 8 9 0) || bspc monitor -d 1 2 3 4 5 6 7 8 9 0

 
#Border gaps,width, and padding
bspc config border_width         1
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config normal_border_color "#db5b05"
bspc config focused_border_color "#3296b4"
 
bspc config top_padding          50
bspc config bottom_padding       8
bspc config left_padding         7
bspc config right_padding        7
 
#bspc rule -a URxvt desktop='^1' follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a Evince desktop='^5'follow=on
 
#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Mouse controls for floating windows
bspc config pointer_modifier mod4
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
