#! /bin/sh

# launch polybar safely
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c ~/.config/polybar/config.ini main &

xsetroot -cursor_name left_ptr
sxhkd &
nitrogen --restore &
picom --experimental-backends &
mpd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
start-pulseaudio-x11
stalonetray &
xfce4-power-manager &
nm-applet &
blueman-applet &
pasystray -m 100 &
dunst &
udiskie &
#cbatticon -u 10 -x "notify-send $(cat /sys/class/power_supply/BAT1/capacity)" &
# Scratch term
st -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on
#### WORKSPACES AND BORDERS ####
 
#Monitor allocation and their workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9  
 
#Border gaps,width, and padding
bspc config border_width         0.5
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          65
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
 
#bspc rule -a URxvt desktop='^1' follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a Evince desktop='^5'follow=on
 
#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
